// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
Future main() async {
  // To load the .env file contents into dotenv.
  // NOTE: fileName defaults to .env and can be omitted in this case.
  // Ensure that the filename corresponds to the path in step 1 and 2.
  await dotenv.load(fileName: ".env");
  //...runapp
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WebapiKey']!,
    appId: dotenv.env['WebappId']!,
    messagingSenderId: dotenv.env['WebmessagingSenderId']!,
    projectId: dotenv.env['WebprojectId']!,
    authDomain: dotenv.env['WebauthDomain']!,
    storageBucket: dotenv.env['WebstorageBucket']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['AndroidapiKey']!,
    appId: dotenv.env['AndroidappId']!,
    messagingSenderId: dotenv.env['AndroidmessagingSenderId']!,
    projectId: dotenv.env['AndroidprojectId']!,
    storageBucket: dotenv.env['AndroidstorageBucket']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOSapiKey']!,
    appId: dotenv.env['IOSappId']!,
    messagingSenderId: dotenv.env['IOSmessagingSenderId']!,
    projectId: dotenv.env['IOSprojectId']!,
    storageBucket: dotenv.env['IOSstorageBucket']!,
    iosBundleId: dotenv.env['IOSBundleId']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MacOSapiKey']!,
    appId: dotenv.env['MacOSappId']!,
    messagingSenderId: dotenv.env['MacOSmessagingSenderId']!,
    projectId: dotenv.env['MacOSprojectId']!,
    storageBucket: dotenv.env['MacOSstorageBucket']!,
    iosBundleId: dotenv.env['MacOSBundleId']!,
  );
}
