// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycnD0YBiuARxtgU_Th2lp4zEUlUcCAQI',
    appId: '1:1041559618983:web:b4b97bf506361177b36282',
    messagingSenderId: '1041559618983',
    projectId: 'the-dram-club-3eb71',
    authDomain: 'the-dram-club-3eb71.firebaseapp.com',
    storageBucket: 'the-dram-club-3eb71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTWtgqGWeX9yuNlxOq9gVLL3yG1Oibxg',
    appId: '1:1041559618983:android:923b16c563cad741b36282',
    messagingSenderId: '1041559618983',
    projectId: 'the-dram-club-3eb71',
    storageBucket: 'the-dram-club-3eb71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5KLLUQ4c9XUxSKkquHoFh2RqLDsotsQ',
    appId: '1:1041559618983:ios:1b2a6ea5b3f411fdb36282',
    messagingSenderId: '1041559618983',
    projectId: 'the-dram-club-3eb71',
    storageBucket: 'the-dram-club-3eb71.appspot.com',
    iosBundleId: 'com.example.theDramClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5KLLUQ4c9XUxSKkquHoFh2RqLDsotsQ',
    appId: '1:1041559618983:ios:fcf414af2611d882b36282',
    messagingSenderId: '1041559618983',
    projectId: 'the-dram-club-3eb71',
    storageBucket: 'the-dram-club-3eb71.appspot.com',
    iosBundleId: 'com.example.theDramClub.RunnerTests',
  );
}
